language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:

env:
  matrix:
    - REQUIRE=dev

before_script:
    - travis_retry composer self-update
    - travis_retry composer --${REQUIRE} --no-interaction --prefer-source install

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml -c test/phpunit.dist.xml

after_script:
    - php vendor/bin/coveralls -v
